const express = require('express');
const session = require('express-session');
const bodyParser = require('body-parser');
const flash = require('connect-flash');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));
app.set('view engine', 'ejs');

// Session Setup
app.use(session({
    secret: 'secret_key_portfolio_admin', // Change this in production
    resave: false,
    saveUninitialized: false
}));
app.use(flash());

// Helper function to read data
const getData = () => {
    const dataPath = path.join(__dirname, 'data', 'portfolio-data.json');
    try {
        const data = fs.readFileSync(dataPath, 'utf8');
        return JSON.parse(data);
    } catch (err) {
        console.error("Error reading data:", err);
        return {};
    }
};

// Helper function to write data
const saveData = (data) => {
    const dataPath = path.join(__dirname, 'data', 'portfolio-data.json');
    try {
        fs.writeFileSync(dataPath, JSON.stringify(data, null, 4), 'utf8');
        return true;
    } catch (err) {
        console.error("Error writing data:", err);
        return false;
    }
};

// Authentication Middleware
const isAuthenticated = (req, res, next) => {
    if (req.session.user) {
        return next();
    }
    res.redirect('/admin/login');
};

// -- ROUTES --

// Dynamic data.js route
app.get('/data.js', (req, res) => {
    const data = getData();
    const scriptContent = `
// Info: Generated by Server
const portfolioData = ${JSON.stringify(data, null, 4)};

// Global accessor for pages to use
window.portfolioData = portfolioData;
    `;
    res.setHeader('Content-Type', 'application/javascript');
    res.send(scriptContent);
});

// Admin Routes
app.get('/admin', (req, res) => {
    if (req.session.user) {
        res.redirect('/admin/dashboard');
    } else {
        res.redirect('/admin/login');
    }
});

app.get('/admin/login', (req, res) => {
    res.render('login', { message: req.flash('error') });
});

app.post('/admin/login', (req, res) => {
    const { username, password } = req.body;
    // Hardcoded credentials for now
    if (username === 'admin' && password === 'admin123') {
        req.session.user = username;
        res.redirect('/admin/dashboard');
    } else {
        req.flash('error', 'Invalid username or password');
        res.redirect('/admin/login');
    }
});

app.get('/admin/logout', (req, res) => {
    req.session.destroy();
    res.redirect('/');
});

app.get('/admin/dashboard', isAuthenticated, (req, res) => {
    const data = getData();
    res.render('dashboard', { data });
});

// Edit Section (List or Form)
app.get('/admin/edit/:section', isAuthenticated, (req, res) => {
    const { section } = req.params;
    const data = getData();

    if (!data[section]) {
        req.flash('error', `Section ${section} not found.`);
        return res.redirect('/admin/dashboard');
    }

    if (Array.isArray(data[section])) {
        // Render List View
        res.render('list', { section, items: data[section] });
    } else {
        // Render Form View for Single Object
        res.render('form', { section, item: data[section], id: null });
    }
});

// Edit specific item in a list
app.get('/admin/edit/:section/:id', isAuthenticated, (req, res) => {
    const { section, id } = req.params;
    const data = getData();

    if (!data[section] || !Array.isArray(data[section])) {
        return res.redirect('/admin/dashboard');
    }

    if (id === 'new') {
        // Empty item for new entry
        // Try to infer schema from first item if exists, else empty
        const schemaItem = data[section].length > 0 ? data[section][0] : {};
        const emptyItem = Object.keys(schemaItem).reduce((acc, key) => {
            acc[key] = ''; // Default empty string
            return acc;
        }, {});
        if (section === 'projects' || section === 'blog') emptyItem.id = Date.now(); // Auto ID

        res.render('form', { section, item: emptyItem, id: 'new' });
    } else {
        const item = data[section].find(i => i.id == id);
        if (!item) {
            req.flash('error', 'Item not found');
            return res.redirect(`/admin/edit/${section}`);
        }
        res.render('form', { section, item, id });
    }
});

// Save Route - Create New
app.post('/admin/save/:section', isAuthenticated, (req, res) => {
    handleSave(req, res);
});

// Save Route - Update Existing
app.post('/admin/save/:section/:id', isAuthenticated, (req, res) => {
    handleSave(req, res);
});

const handleSave = (req, res) => {
    const { section, id } = req.params;
    const updatedItem = req.body;
    const data = getData();

    // Get schema/type info from existing data if possible
    let existingItem = null;
    if (Array.isArray(data[section])) {
        if (id && id !== 'new') {
            existingItem = data[section].find(i => i.id == id);
        } else if (data[section].length > 0) {
            existingItem = data[section][0]; // infer from first item
        }
    } else {
        existingItem = data[section];
    }

    // Process fields
    for (let key in updatedItem) {
        let originalValue = existingItem ? existingItem[key] : null;
        let incomingValue = updatedItem[key];

        const tryParseJSON = (str) => {
            try { return JSON.parse(str); } catch (e) { return null; }
        };

        if (typeof incomingValue === 'string') {
            // Check if it's supposed to be an array of objects or an object
            if (originalValue && typeof originalValue === 'object') {
                const parsed = tryParseJSON(incomingValue);
                if (parsed) {
                    updatedItem[key] = parsed;
                } else if (Array.isArray(originalValue) && (key === 'tech' || key === 'tags')) {
                    // Fallback for simple arrays handled as CSV
                    updatedItem[key] = incomingValue.split(',').map(s => s.trim()).filter(s => s);
                }
            }
        }
    }

    if (Array.isArray(data[section])) {
        if (id === 'new' || !id) {
            // Add new
            if (!updatedItem.id) updatedItem.id = Date.now();
            data[section].push(updatedItem);
        } else {
            // Update existing
            const index = data[section].findIndex(i => i.id == id);
            if (index !== -1) {
                // Merge
                data[section][index] = { ...data[section][index], ...updatedItem };
            }
        }
    } else {
        // Update Single Object
        data[section] = { ...data[section], ...updatedItem };
    }

    saveData(data);
    req.flash('success', 'Saved successfully');

    if (Array.isArray(data[section])) {
        res.redirect(`/admin/edit/${section}`);
    } else {
        res.redirect(`/admin/edit/${section}`); // Stay on page for single object
    }
};

// Delete Route
app.get('/admin/delete/:section/:id', isAuthenticated, (req, res) => {
    const { section, id } = req.params;
    const data = getData();

    if (Array.isArray(data[section])) {
        data[section] = data[section].filter(i => i.id != id);
        saveData(data);
        req.flash('success', 'Item deleted');
    }

    res.redirect(`/admin/edit/${section}`);
});


// Start Server
app.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}`);
});
